# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://raphael2692.github.io/cv_tools/"

git_url = "https://github.com/raphael2692/cv_tools/tree/master/"

def custom_doc_links(name): return None
